# Generated by Django 5.2.15 on 2026-06-03 23:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wms_id', models.BigIntegerField(unique=True, verbose_name='WMS ID')),
                ('category_code', models.CharField(max_length=30, unique=True, verbose_name='カテゴリコード')),
                ('category_name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('sort_order', models.IntegerField(default=10, verbose_name='表示順')),
                ('is_leaf', models.BooleanField(default=False, verbose_name='商品の登録先')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('wms_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='WMS 更新日時')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='同期日時')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.eccategory', verbose_name='親カテゴリ')),
            ],
            options={
                'verbose_name': 'カテゴリ（コピー）',
                'verbose_name_plural': 'カテゴリ（コピー）',
                'db_table': 'ec_categories',
                'ordering': ['sort_order', 'category_code'],
            },
        ),
        migrations.CreateModel(
            name='EcProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wms_id', models.BigIntegerField(unique=True, verbose_name='WMS ID')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='商品コード')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('wms_manufacturer_id', models.BigIntegerField(blank=True, null=True, verbose_name='WMS メーカー ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品画像')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('wms_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='WMS 更新日時')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='同期日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.eccategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '商品（コピー）',
                'verbose_name_plural': '商品（コピー）',
                'db_table': 'ec_products',
            },
        ),
        migrations.CreateModel(
            name='EcSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wms_id', models.BigIntegerField(unique=True, verbose_name='WMS ID')),
                ('sku_code', models.CharField(max_length=50, unique=True, verbose_name='SKUコード')),
                ('jan_code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='JANコード')),
                ('size_info', models.CharField(blank=True, max_length=50, verbose_name='サイズ')),
                ('color_info', models.CharField(blank=True, max_length=50, verbose_name='カラー')),
                ('quantity_per_unit', models.IntegerField(default=1, verbose_name='入数（ケース）')),
                ('picking_type', models.CharField(blank=True, max_length=20, verbose_name='ピッキング種別')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('wms_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='WMS 更新日時')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='同期日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='catalog.ecproduct', verbose_name='商品')),
            ],
            options={
                'verbose_name': 'SKU（コピー）',
                'verbose_name_plural': 'SKU（コピー）',
                'db_table': 'ec_skus',
            },
        ),
        migrations.CreateModel(
            name='EcPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='販売価格（税抜・円）')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4, verbose_name='消費税率')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='catalog.ecsku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '価格',
                'verbose_name_plural': '価格',
                'db_table': 'ec_price_lists',
            },
        ),
    ]
