# Generated by Django 5.2.15 on 2026-06-04 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ecproduct_manufacturer_name'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', '注文確定')], default='confirmed', max_length=20, verbose_name='状態')),
                ('delivery_name', models.CharField(max_length=100, verbose_name='配送先氏名')),
                ('delivery_postal_code', models.CharField(blank=True, max_length=10, verbose_name='配送先郵便番号')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='配送先住所')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='合計金額（税込）')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='備考')),
                ('wms_outbound_order_code', models.CharField(blank=True, max_length=50, verbose_name='WMS 出荷指示番号')),
                ('wms_status', models.CharField(blank=True, max_length=30, verbose_name='WMS 側ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
                'db_table': 'ec_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=50, verbose_name='SKUコード')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('size_info', models.CharField(blank=True, max_length=50, verbose_name='サイズ')),
                ('color_info', models.CharField(blank=True, max_length=50, verbose_name='カラー')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='単価（税込）')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ecsku')),
            ],
            options={
                'verbose_name': '注文明細',
                'verbose_name_plural': '注文明細',
                'db_table': 'ec_order_items',
            },
        ),
    ]
