# Generated by Django 5.2.15 on 2026-06-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '処理中'), ('confirmed', '注文確定')], default='confirmed', max_length=20, verbose_name='状態'),
        ),
    ]
