# Generated by Django 5.2.15 on 2026-06-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['id'], 'verbose_name': 'カート明細', 'verbose_name_plural': 'カート明細'},
        ),
    ]
